### ISSUE TITLE
Re-using struct causes out of range panic

### ISSUE THREAD

**Issue by dcarbone** [myENA/consul-decoder#4]
Given: 
```golang
type (
    ChildPrototype struct {
        Name string
    }
    Parent struct {
        Child1 ChildPrototype
        Child2 ChildPrototype
    }
)
```

Results in (pulled from test I've created):
```
panic: reflect: Field index out of range [recovered]
        panic: reflect: Field index out of range

goroutine 4 [running]:
testing.tRunner.func1(0xc000116200)
        testing/testing.go:792 +0x6a7
panic(0x157c060, 0x168eb40)
       runtime/panic.go:513 +0x1b9
reflect.Value.Field(0x15bbe80, 0xc0004901a0, 0x199, 0x18, 0x15bbe80, 0xc0004901a0, 0x199)
       reflect/value.go:786 +0x2bc
github.com/myENA/consul-decoder.(*Decoder).allocAssign(0xc0003b58e0, 0xc0004713c0, 0xc000255980, 0xc0003b52f0, 0x1601e80, 0xc000490000, 0x199, 0xc000465520, 0x8, 0x0, ...)
        src/github.com/myENA/consul-decoder/decoder.go:474 +0x3f3
github.com/myENA/consul-decoder.(*Decoder).Unmarshal(0xc0003b58e0, 0xc000465520, 0x8, 0xc0002383b0, 0xa, 0xc, 0x15675c0, 0xc000490000, 0x0, 0x0)
        src/github.com/myENA/consul-decoder/decoder.go:444 +0x4f8
github.com/myENA/consul-decoder.(*encoderTestSuite).TestUnmarshal(0xc000087020)
        src/github.com/myENA/consul-decoder/decoder_test.go:239 +0x6d5
reflect.Value.call(0xc0003acd20, 0xc000474068, 0x13, 0x160b987, 0x4, 0xc0003b5f00, 0x1, 0x1, 0xc0003b5de8, 0x1063592, ...)
        src/reflect/value.go:447 +0x62c
reflect.Value.Call(0xc0003acd20, 0xc000474068, 0x13, 0xc0003b5f00, 0x1, 0x1, 0x15473e3, 0xd, 0x0)
        reflect/value.go:308 +0xc1
github.com/myENA/consul-decoder/vendor/github.com/stretchr/testify/suite.Run.func2(0xc000116200)
        src/github.com/myENA/consul-decoder/vendor/github.com/stretchr/testify/suite/suite.go:102 +0x2d0
testing.tRunner(0xc000116200, 0xc00040e080)
        testing/testing.go:827 +0x163
created by testing.(*T).Run
       testing/testing.go:878 +0x651
exit status 2
FAIL    github.com/myENA/consul-decoder 2.004s
```

**Comment by dcarbone** [comment]
It should be noted this only occurs if the same struct is used as sibling fields.  It appears as though either the parseStruct func does not properly retain scope or the Unmarshal func ignores it, as when time comes to unmarshal the 2nd field the logic believes it is unmarshalling the parent, not the child.
